### ISSUE TITLE
Template submission failed

### ISSUE THREAD

**Issue by jdiedrichsen** [templateflow/templateflow#166]
Dear Oscar, 

I am trying to contribute the SUIT (cerebellar only) template to templateflow, following the submission instructions: 
https://www.templateflow.org/contributing/submission/

The file upload does work - however, there seems to be a conflict with something uploaded earlier. 

I'm not sure how to resolve this.... 

best, 

Joern 

```
tfmgr add tpl-SUIT --osf-user jdiedric@uwo.ca
OSF password: 
Has a RRID (research resource ID) already been assigned? []: No
Preparing Pull-Request (wd=/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74).
Cloning into 'templateflow'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 15 (delta 0), reused 2 (delta 0), pack-reused 13
Receiving objects: 100% (15/15), 44.62 MiB | 20.54 MiB/s, done.
Resolving deltas: 100% (1/1), done.
create(error): /private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT (dataset) [collision with content in parent dataset at /private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow: ['/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/LICENSE', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/README.md', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/template_description.json', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT.spec', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_flat.surf.gii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin2009cSymC_mode-image_xfm.nii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin2009cSymC_mode-point_xfm.nii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin6AsymC_mode-image_xfm.nii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin6AsymC_mode-point_xfm.nii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_res-1_T1w.nii', '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_sulc.shape.gii']]
Traceback (most recent call last):
  File "/opt/miniconda3/bin/tfmgr", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/tfmanager/cli.py", line 221, in add
    dl.create(
  File "/opt/miniconda3/lib/python3.9/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.9/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
  File "/opt/miniconda3/lib/python3.9/site-packages/datalad_next/patches/interface_utils.py", line 287, in _execute_command_
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'create',
  'message': ('collision with content in parent dataset at %s: %s',
              '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow',
              ['/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/LICENSE',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/README.md',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/template_description.json',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT.spec',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_flat.surf.gii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin2009cSymC_mode-image_xfm.nii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin2009cSymC_mode-point_xfm.nii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin6AsymC_mode-image_xfm.nii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_from-MNI152NLin6AsymC_mode-point_xfm.nii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_res-1_T1w.nii',
               '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT/tpl-SUIT_sulc.shape.gii']),
  'path': '/private/var/folders/vh/tsrrmndj3kj8fm3m4p51k3nc0000gn/T/tmpzezi_c74/templateflow/tpl-SUIT',
  'refds': None,
  'status': 'error',
  'type': 'dataset'}]
```

**Comment by oesteban** [comment]
Sorry, sorry, sorry -- I've been up to my eyeballs and totally forgot about this :(

First, I'm going to move this comment to the template manager. It looks like an error on your computer's side.

However, I don't want to keep you stuck with this, so if you zip up the template and send it to me, I'll make sure to publish it before Tuesday.

Again, thanks a lot for your incredible patience (since September, when you first contacted me).
