### ISSUE TITLE
Add template SPM152 (older adults)

### ISSUE THREAD

**Issue by oesteban** [templateflow/templateflow#19]
As proposed in https://neurostars.org/t/older-adult-mni-template/5125, find out whether https://www.ncbi.nlm.nih.gov/pubmed/22440645 can be redistributed within TemplateFlow.

**Comment by oesteban** [comment]
*Lisa_Marie* on neurostars reminds me of this template, and checking on the paper I see that @neurolabusc is the first author. Can I ask you whether the template is distributed under a permissive license (we would need to be able to redistribute and to derive some metadata -headers, etc.-)?

**Comment by neurolabusc** [comment]
@oesteban the [template](https://github.com/neurolabusc/Clinical) uses the [BSD 2 Clause license](https://opensource.org/licenses/BSD-2-Clause) so you are free to re-distribute with attribution (this could be simply a link in the NIfTI `description` tag).

The caveats I mentioned in [neurostars](https://neurostars.org/t/older-adult-mni-template/5125) remain
 - This template is in SPM space (average sized brain) which is slightly [smaller than typical MNI templates](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6050588/).
 - John E Richards now has age specific templates based on [a larger sample](https://jerlab.sc.edu/projects/neurodevelopmental-mri-database/).

**Comment by dkp** [comment]
Any news on this?  We really need an older adult template for fmriprep.  Thank you.

**Comment by oesteban** [comment]
I checked with Prof. Richards, but his templates are not open. I'm quite swamped right now, but I'll be happy to assist anyone who would be interested in adding Prof. Rorden's template.

**Comment by neurolabusc** [comment]
@oesteban John Richards does plan to share the dataset once it survives peer review. I suspect this to happen by the end of this semester, so you may wish to defer. You are free to use my templates as well.

**Comment by oesteban** [comment]
Sure, I think we had a conversation a couple of years ago. I thought I clearly stated I didn't want to release his data, only the templates themselves, bringing up similar concerns (at that point, it was the impending decision on a grant, that was before the NIH mandate). We likely did not understand each other.

He is already sharing some or all data, but the terms are completely incompatible with redistribution.

Anyways, templates are not mutually exclusive for templateflow, so we will start with yours and perhaps in the future the circumstances align to complete with other alternatives.

@dkp if you are still interested, I can walk you through the template preparation and submission process.

**Comment by dkp** [comment]
@oesteban thank you so much!  Right now I'm trying to create a local template using the MIITRA atlas that fmriprep can use.  I am using Docker and I have bind-mounted the directory...but about halfway through the processing fmriprep hangs claiming

```bash
	traits.trait_errors.TraitError: The 'brain_mask' trait of a _TemplateFlowSelectOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '[]' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '[]' for output 'brain_mask' of a TemplateFlowSelect interface
```

Here's my atlas attempt: https://www.dropbox.com/s/bv3d2v5ve5iz29a/tpl-MIITRA.zip?dl=0
I got fmriprep to run if I did not specify res-01 (but it produced results only in native space).

If I specify a resolution, then it hangs.  Here's my fmriprep docker call:

```bash
# MIITRA version
# docker run --rm -it \
#  -v /Users/dpat/license.txt:/opt/freesurfer/license.txt:ro \
#  -v "${PWD}"/inputs/bids:/data:ro \
#  -v "${PWD}"/outputs/derivatives:/out \
#  -v "${PWD}"/fmriprep_work:/work \
#  -v "${PWD}"/inputs/TemplateFlow_Example/tpl-MIITRA:/home/fmriprep/.cache/templateflow/tpl-MIITRA:ro \
# nipreps/fmriprep:22.1.1 /data /out participant --participant_label CAM003 -w /work --stop-on-first-crash --ignore slicetiming  --fs-no-reconall -v -v  --output-spaces MIITRA:res-01
```

I'd appreciate any suggestions.  I'm missing something about how this works.

-Dianne
