### ISSUE TITLE
Can't import in docker with Ubuntu 18.04: UnicodeDecodeError raised in pybids

### ISSUE THREAD

**Issue by arokem** [templateflow/templateflow#67]
Previously reported by @soichih here: https://github.com/yeatmanlab/pyAFQ/issues/267

To reproduce, build with the following Dockerfile

```
FROM ubuntu:18.04

RUN apt-get update && apt-get -y install \
    python3 \
    python3-pip \
    jq \
    time \
    git \
    curl \
    unzip \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl-dev

RUN pip3 install templateflow
```
built (in my case) with:

```
docker build . -t arokem/tflow_test:0.02
```

And running 

```
docker run -it arokem/tflow_test:0.01 python3 -c"from templateflow import API"
```

produces:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/templateflow/api.py", line 6, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD
  File "/usr/local/lib/python3.6/dist-packages/templateflow/conf/__init__.py", line 81, in <module>
    ignore=['.git', '.datalad', '.gitannex', '.gitattributes', 'scripts'])
  File "/usr/local/lib/python3.6/dist-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/lib/python3.6/dist-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 804: ordinal not in range(128)
```

I am not sure what this is, but I am not seeing this on the pyAFQ CI, which leads me to suspect this has to do with OS

**Comment by arokem** [comment]
Oh no - I am wrong. Running: 

```
docker run -it arokem/tflow_test:0.02 python3 -c"from templateflow import api"
```

(the right version of the image) doesn't raise the error. Seems like a problem in pyAFQ, not here.

**Comment by soichih** [comment]
This fails ..

```
$ singularity exec docker://brainlife/pyafq:1.0 python3 -c"from templateflow import api"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/templateflow/api.py", line 6, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD
  File "/usr/local/lib/python3.6/site-packages/templateflow/conf/__init__.py", line 81, in <module>
    ignore=['.git', '.datalad', '.gitannex', '.gitattributes', 'scripts'])
  File "/usr/local/lib/python3.6/site-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/lib/python3.6/site-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/local/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 804: ordinal not in range(128)
You have new mail in /var/mail/hayashis

```

I tried to prefetch the template like fmriprep container does, but it didn't work. Here is my attempt.

```
ENV TEMPLATEFLOW_HOME=/templateflow
RUN python3 -c "from templateflow import api as tfapi; \
               tfapi.get('MNI152NLin6Asym', atlas=None, resolution=[1, 2], \
                         desc=None, extension=['.nii', '.nii.gz']); \
               tfapi.get('MNI152NLin6Asym', atlas=None, resolution=[1, 2], \
                         desc='brain', extension=['.nii', '.nii.gz']); \
               tfapi.get('MNI152NLin2009cAsym', atlas=None, extension=['.nii', '.nii.gz']); \
               tfapi.get('OASIS30ANTs', extension=['.nii', '.nii.gz']); \
               tfapi.get('fsaverage', density='164k', desc='std', suffix='sphere'); \
               tfapi.get('fsaverage', density='164k', desc='vaavg', suffix='midthickness'); \
               tfapi.get('fsLR', density='32k'); \
               tfapi.get('MNI152NLin6Asym', resolution=2, atlas='HCP', suffix='dseg')"
RUN chmod -R go=u /templateflow
```

I am still seeing the same error message.

I still think templateflow might be trying to access file system where it shouldn't.. or there is something wrong with one of the json file? Can someone from templateflow look at this issue?

**Comment by oesteban** [comment]
I guess this is not doing what you think it does (in the context of the Singularity image):
```
RUN chmod -R go=u /templateflow
```

or are you running the image on privileged mode, @soichih ?

If not, you'll need to bind mount some writable folder on to `/templateflow`. Otherwise Singularity will not let you write on a container's filesystem if it is not privileged.

**Comment by soichih** [comment]
@oesteban I am prefetching the templateflow content in the Dockerfile so that /templateflow will be part of the container, and thus part of the singularity container. fmriprep container does the similar trick to get it working, but for some reason it's not working for me.

This still fails, btw

```
singularity exec docker://brainlife/pyafq:1.0 python3 -c"from templateflow import api"
```

Do you see any reason why it would fail?
